# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Presentacion/UI_Files/PaginaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(913, 725)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(300, 500))
        self.widget_2.setStyleSheet("background-color: rgb(164, 0, 0);")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.widgetOpciones = QtWidgets.QTabWidget(self.centralwidget)
        self.widgetOpciones.setMinimumSize(QtCore.QSize(300, 500))
        self.widgetOpciones.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widgetOpciones.setObjectName("widgetOpciones")
        self.tab_test = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_test.sizePolicy().hasHeightForWidth())
        self.tab_test.setSizePolicy(sizePolicy)
        self.tab_test.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_test.setObjectName("tab_test")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_test)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.tab_test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.input_buscar_contacto = QtWidgets.QLineEdit(self.tab_test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_buscar_contacto.sizePolicy().hasHeightForWidth())
        self.input_buscar_contacto.setSizePolicy(sizePolicy)
        self.input_buscar_contacto.setMaximumSize(QtCore.QSize(500, 16777215))
        self.input_buscar_contacto.setObjectName("input_buscar_contacto")
        self.verticalLayout_2.addWidget(self.input_buscar_contacto)
        self.btn_buscar_contacto = QtWidgets.QPushButton(self.tab_test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_buscar_contacto.sizePolicy().hasHeightForWidth())
        self.btn_buscar_contacto.setSizePolicy(sizePolicy)
        self.btn_buscar_contacto.setMaximumSize(QtCore.QSize(500, 16777215))
        self.btn_buscar_contacto.setObjectName("btn_buscar_contacto")
        self.verticalLayout_2.addWidget(self.btn_buscar_contacto)
        self.label_2 = QtWidgets.QLabel(self.tab_test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.input_insertar_msg = QtWidgets.QLineEdit(self.tab_test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_insertar_msg.sizePolicy().hasHeightForWidth())
        self.input_insertar_msg.setSizePolicy(sizePolicy)
        self.input_insertar_msg.setMaximumSize(QtCore.QSize(500, 16777215))
        self.input_insertar_msg.setObjectName("input_insertar_msg")
        self.verticalLayout_2.addWidget(self.input_insertar_msg)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.label_3 = QtWidgets.QLabel(self.tab_test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMaximumSize(QtCore.QSize(500, 16777215))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.label_4 = QtWidgets.QLabel(self.tab_test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMaximumSize(QtCore.QSize(500, 16777215))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.label_5 = QtWidgets.QLabel(self.tab_test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMaximumSize(QtCore.QSize(500, 16777215))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.widgetOpciones.addTab(self.tab_test, "")
        self.tab_Mensaje = QtWidgets.QWidget()
        self.tab_Mensaje.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_Mensaje.sizePolicy().hasHeightForWidth())
        self.tab_Mensaje.setSizePolicy(sizePolicy)
        self.tab_Mensaje.setMinimumSize(QtCore.QSize(300, 300))
        self.tab_Mensaje.setMaximumSize(QtCore.QSize(123312, 2312131))
        self.tab_Mensaje.setAutoFillBackground(False)
        self.tab_Mensaje.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.tab_Mensaje.setObjectName("tab_Mensaje")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_Mensaje)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_Enviar_nuevo_mensaje = QtWidgets.QLabel(self.tab_Mensaje)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_Enviar_nuevo_mensaje.sizePolicy().hasHeightForWidth())
        self.lbl_Enviar_nuevo_mensaje.setSizePolicy(sizePolicy)
        self.lbl_Enviar_nuevo_mensaje.setMinimumSize(QtCore.QSize(0, 50))
        self.lbl_Enviar_nuevo_mensaje.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 27pt \"Inter\";")
        self.lbl_Enviar_nuevo_mensaje.setObjectName("lbl_Enviar_nuevo_mensaje")
        self.gridLayout_2.addWidget(self.lbl_Enviar_nuevo_mensaje, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 2, 1, 1)
        self.btn_enviar_msg = QtWidgets.QPushButton(self.tab_Mensaje)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_enviar_msg.sizePolicy().hasHeightForWidth())
        self.btn_enviar_msg.setSizePolicy(sizePolicy)
        self.btn_enviar_msg.setStyleSheet("background-color: rgb(115, 210, 22);")
        self.btn_enviar_msg.setObjectName("btn_enviar_msg")
        self.gridLayout_2.addWidget(self.btn_enviar_msg, 3, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 0, 2, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_Mensaje)
        self.plainTextEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_2.addWidget(self.plainTextEdit, 2, 2, 1, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 4)
        self.gridLayout_2.setColumnStretch(3, 1)
        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setRowStretch(1, 3)
        self.gridLayout_2.setRowStretch(2, 3)
        self.gridLayout_2.setRowStretch(3, 3)
        self.gridLayout_2.setRowStretch(4, 1)
        self.widgetOpciones.addTab(self.tab_Mensaje, "")
        self.tab_AdminMsg = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_AdminMsg.sizePolicy().hasHeightForWidth())
        self.tab_AdminMsg.setSizePolicy(sizePolicy)
        self.tab_AdminMsg.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.tab_AdminMsg.setObjectName("tab_AdminMsg")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_AdminMsg)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_AdminMsg)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 0, 1, 1)
        self.widgetOpciones.addTab(self.tab_AdminMsg, "")
        self.tab_AdminGrp = QtWidgets.QWidget()
        self.tab_AdminGrp.setObjectName("tab_AdminGrp")
        self.widgetOpciones.addTab(self.tab_AdminGrp, "")
        self.horizontalLayout_2.addWidget(self.widgetOpciones)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 913, 27))
        self.menubar.setObjectName("menubar")
        self.menuAjustes = QtWidgets.QMenu(self.menubar)
        self.menuAjustes.setObjectName("menuAjustes")
        self.menuOpciones = QtWidgets.QMenu(self.menubar)
        self.menuOpciones.setObjectName("menuOpciones")
        self.menuOpciones_2 = QtWidgets.QMenu(self.menuOpciones)
        self.menuOpciones_2.setObjectName("menuOpciones_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAjustes_1 = QtWidgets.QAction(MainWindow)
        self.actionAjustes_1.setObjectName("actionAjustes_1")
        self.actionOpciones_1 = QtWidgets.QAction(MainWindow)
        self.actionOpciones_1.setObjectName("actionOpciones_1")
        self.actionOpciones_2_1 = QtWidgets.QAction(MainWindow)
        self.actionOpciones_2_1.setObjectName("actionOpciones_2_1")
        self.actionOpciones_2_2 = QtWidgets.QAction(MainWindow)
        self.actionOpciones_2_2.setObjectName("actionOpciones_2_2")
        self.actionAbrir_guasa = QtWidgets.QAction(MainWindow)
        self.actionAbrir_guasa.setObjectName("actionAbrir_guasa")
        self.menuAjustes.addAction(self.actionAjustes_1)
        self.menuAjustes.addAction(self.actionAbrir_guasa)
        self.menuOpciones_2.addAction(self.actionOpciones_2_1)
        self.menuOpciones_2.addAction(self.actionOpciones_2_2)
        self.menuOpciones.addAction(self.actionOpciones_1)
        self.menuOpciones.addAction(self.menuOpciones_2.menuAction())
        self.menubar.addAction(self.menuAjustes.menuAction())
        self.menubar.addAction(self.menuOpciones.menuAction())

        self.retranslateUi(MainWindow)
        self.widgetOpciones.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pantalla Principal"))
        self.label.setText(_translate("MainWindow", "Buscar Numero"))
        self.btn_buscar_contacto.setText(_translate("MainWindow", "Buscar"))
        self.label_2.setText(_translate("MainWindow", "Insertar Mensaje"))
        self.pushButton_2.setText(_translate("MainWindow", "Insertar"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.widgetOpciones.setTabText(self.widgetOpciones.indexOf(self.tab_test), _translate("MainWindow", "Test"))
        self.lbl_Enviar_nuevo_mensaje.setText(_translate("MainWindow", "Nuevo mensaje"))
        self.btn_enviar_msg.setText(_translate("MainWindow", "Enviar"))
        self.widgetOpciones.setTabText(self.widgetOpciones.indexOf(self.tab_Mensaje), _translate("MainWindow", "Nuevo Mensaje"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.widgetOpciones.setTabText(self.widgetOpciones.indexOf(self.tab_AdminMsg), _translate("MainWindow", "Mensajes"))
        self.widgetOpciones.setTabText(self.widgetOpciones.indexOf(self.tab_AdminGrp), _translate("MainWindow", "Grupos"))
        self.menuAjustes.setTitle(_translate("MainWindow", "A&justes"))
        self.menuOpciones.setTitle(_translate("MainWindow", "Opciones"))
        self.menuOpciones_2.setTitle(_translate("MainWindow", "Opciones &2"))
        self.actionAjustes_1.setText(_translate("MainWindow", "&Ajustes 1"))
        self.actionOpciones_1.setText(_translate("MainWindow", "&Opciones 1"))
        self.actionOpciones_2_1.setText(_translate("MainWindow", "&Opciones 2.1"))
        self.actionOpciones_2_2.setText(_translate("MainWindow", "Opciones &2.2"))
        self.actionAbrir_guasa.setText(_translate("MainWindow", "Abrir &guasa"))
